services:
  - type: web
    name: moodify-backend
    env: python
    buildCommand: |
      pip install -r requirements.txt
      npm install --prefix frontend
      npm run build --prefix frontend
    startCommand: gunicorn app:app
    plan: free
